<?php
/**
 * AuthenticationApiTest
 * PHP version 8.1
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Semaphore API
 *
 * Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models.
 *
 * The version of the OpenAPI document: 2.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientAPI\Semaphore\Test\Api;

use ClientAPI\Semaphore\Configuration;
use ClientAPI\Semaphore\ApiException;
use ClientAPI\Semaphore\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AuthenticationApiTest Class Doc Comment
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthenticationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for authLoginGet
     *
     * Fetches login metadata.
     *
     */
    public function testAuthLoginGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authLoginPost
     *
     * Performs Login.
     *
     */
    public function testAuthLoginPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authLogoutPost
     *
     * Destroys current session.
     *
     */
    public function testAuthLogoutPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authOidcProviderIdLoginGet
     *
     * Begin OIDC authentication flow and redirect to OIDC provider.
     *
     */
    public function testAuthOidcProviderIdLoginGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authOidcProviderIdRedirectGet
     *
     * Finish OIDC authentication flow, upon succes you will be logged in.
     *
     */
    public function testAuthOidcProviderIdRedirectGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userTokensApiTokenIdDelete
     *
     * Expires API token.
     *
     */
    public function testUserTokensApiTokenIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userTokensGet
     *
     * Fetch API tokens for user.
     *
     */
    public function testUserTokensGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userTokensPost
     *
     * Create an API token.
     *
     */
    public function testUserTokensPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
