<?php
/**
 * IntegrationApiTest
 * PHP version 8.1
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Semaphore API
 *
 * Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models.
 *
 * The version of the OpenAPI document: 2.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientAPI\Semaphore\Test\Api;

use ClientAPI\Semaphore\Configuration;
use ClientAPI\Semaphore\ApiException;
use ClientAPI\Semaphore\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IntegrationApiTest Class Doc Comment
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IntegrationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdMatchersGet
     *
     * Get Integration Matcher linked to integration extractor.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdMatchersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdMatchersMatcherIdDelete
     *
     * Removes integration matcher.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdMatchersMatcherIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdMatchersMatcherIdPut
     *
     * Updates Integration Matcher.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdMatchersMatcherIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdValuesExtractvalueIdDelete
     *
     * Removes integration extract value.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdValuesExtractvalueIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdValuesExtractvalueIdPut
     *
     * Updates Integration ExtractValue.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdValuesExtractvalueIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdValuesGet
     *
     * Get Integration Extracted Values linked to integration extractor.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdValuesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
