<?php
/**
 * ProjectApiTest
 * PHP version 8.1
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Semaphore API
 *
 * Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models.
 *
 * The version of the OpenAPI document: 2.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientAPI\Semaphore\Test\Api;

use ClientAPI\Semaphore\Configuration;
use ClientAPI\Semaphore\ApiException;
use ClientAPI\Semaphore\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectApiTest Class Doc Comment
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for projectProjectIdBackupGet
     *
     * Backup A Project.
     *
     */
    public function testProjectProjectIdBackupGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdDelete
     *
     * Delete project.
     *
     */
    public function testProjectProjectIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdEnvironmentEnvironmentIdDelete
     *
     * Removes environment.
     *
     */
    public function testProjectProjectIdEnvironmentEnvironmentIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdEnvironmentEnvironmentIdGet
     *
     * Get environment.
     *
     */
    public function testProjectProjectIdEnvironmentEnvironmentIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdEnvironmentEnvironmentIdPut
     *
     * Update environment.
     *
     */
    public function testProjectProjectIdEnvironmentEnvironmentIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdEnvironmentGet
     *
     * Get environment.
     *
     */
    public function testProjectProjectIdEnvironmentGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdEnvironmentPost
     *
     * Add environment.
     *
     */
    public function testProjectProjectIdEnvironmentPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdEventsGet
     *
     * Get Events related to this project.
     *
     */
    public function testProjectProjectIdEventsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdGet
     *
     * Fetch project.
     *
     */
    public function testProjectProjectIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsGet
     *
     * get all integrations.
     *
     */
    public function testProjectProjectIdIntegrationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdDelete
     *
     * Remove integration.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdMatchersPost
     *
     * Add Integration Matcher.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdMatchersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdPut
     *
     * Update Integration.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsIntegrationIdValuesPost
     *
     * Add Integration Extracted Value.
     *
     */
    public function testProjectProjectIdIntegrationsIntegrationIdValuesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdIntegrationsPost
     *
     * create a new integration.
     *
     */
    public function testProjectProjectIdIntegrationsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdInventoryGet
     *
     * Get inventory.
     *
     */
    public function testProjectProjectIdInventoryGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdInventoryInventoryIdDelete
     *
     * Removes inventory.
     *
     */
    public function testProjectProjectIdInventoryInventoryIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdInventoryInventoryIdGet
     *
     * Get inventory.
     *
     */
    public function testProjectProjectIdInventoryInventoryIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdInventoryInventoryIdPut
     *
     * Updates inventory.
     *
     */
    public function testProjectProjectIdInventoryInventoryIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdInventoryPost
     *
     * create inventory.
     *
     */
    public function testProjectProjectIdInventoryPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdKeysGet
     *
     * Get access keys linked to project.
     *
     */
    public function testProjectProjectIdKeysGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdKeysKeyIdDelete
     *
     * Removes access key.
     *
     */
    public function testProjectProjectIdKeysKeyIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdKeysKeyIdPut
     *
     * Updates access key.
     *
     */
    public function testProjectProjectIdKeysKeyIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdKeysPost
     *
     * Add access key.
     *
     */
    public function testProjectProjectIdKeysPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdPut
     *
     * Update project.
     *
     */
    public function testProjectProjectIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdRepositoriesGet
     *
     * Get repositories.
     *
     */
    public function testProjectProjectIdRepositoriesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdRepositoriesPost
     *
     * Add repository.
     *
     */
    public function testProjectProjectIdRepositoriesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdRepositoriesRepositoryIdDelete
     *
     * Removes repository.
     *
     */
    public function testProjectProjectIdRepositoriesRepositoryIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdRepositoriesRepositoryIdGet
     *
     * Get repository.
     *
     */
    public function testProjectProjectIdRepositoriesRepositoryIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdRepositoriesRepositoryIdPut
     *
     * Updates repository.
     *
     */
    public function testProjectProjectIdRepositoriesRepositoryIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdRoleGet
     *
     * Fetch permissions of the current user for project.
     *
     */
    public function testProjectProjectIdRoleGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTasksGet
     *
     * Get Tasks related to current project.
     *
     */
    public function testProjectProjectIdTasksGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTasksLastGet
     *
     * Get last 200 Tasks related to current project.
     *
     */
    public function testProjectProjectIdTasksLastGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTasksPost
     *
     * Starts a job.
     *
     */
    public function testProjectProjectIdTasksPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTasksTaskIdDelete
     *
     * Deletes task (including output).
     *
     */
    public function testProjectProjectIdTasksTaskIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTasksTaskIdGet
     *
     * Get a single task.
     *
     */
    public function testProjectProjectIdTasksTaskIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTasksTaskIdOutputGet
     *
     * Get task output.
     *
     */
    public function testProjectProjectIdTasksTaskIdOutputGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTasksTaskIdStopPost
     *
     * Stop a job.
     *
     */
    public function testProjectProjectIdTasksTaskIdStopPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTemplatesGet
     *
     * Get template.
     *
     */
    public function testProjectProjectIdTemplatesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTemplatesPost
     *
     * create template.
     *
     */
    public function testProjectProjectIdTemplatesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTemplatesTemplateIdDelete
     *
     * Removes template.
     *
     */
    public function testProjectProjectIdTemplatesTemplateIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTemplatesTemplateIdGet
     *
     * Get template.
     *
     */
    public function testProjectProjectIdTemplatesTemplateIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdTemplatesTemplateIdPut
     *
     * Updates template.
     *
     */
    public function testProjectProjectIdTemplatesTemplateIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdUsersGet
     *
     * Get users linked to project.
     *
     */
    public function testProjectProjectIdUsersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdUsersPost
     *
     * Link user to project.
     *
     */
    public function testProjectProjectIdUsersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdUsersUserIdDelete
     *
     * Removes user from project.
     *
     */
    public function testProjectProjectIdUsersUserIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdUsersUserIdPut
     *
     * Update user role.
     *
     */
    public function testProjectProjectIdUsersUserIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdViewsGet
     *
     * Get view.
     *
     */
    public function testProjectProjectIdViewsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdViewsPost
     *
     * create view.
     *
     */
    public function testProjectProjectIdViewsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdViewsViewIdDelete
     *
     * Removes view.
     *
     */
    public function testProjectProjectIdViewsViewIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdViewsViewIdGet
     *
     * Get view.
     *
     */
    public function testProjectProjectIdViewsViewIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdViewsViewIdPut
     *
     * Updates view.
     *
     */
    public function testProjectProjectIdViewsViewIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
