<?php
/**
 * ScheduleApiTest
 * PHP version 8.1
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Semaphore API
 *
 * Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models.
 *
 * The version of the OpenAPI document: 2.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientAPI\Semaphore\Test\Api;

use ClientAPI\Semaphore\Configuration;
use ClientAPI\Semaphore\ApiException;
use ClientAPI\Semaphore\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ScheduleApiTest Class Doc Comment
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScheduleApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for projectProjectIdSchedulesPost
     *
     * create schedule.
     *
     */
    public function testProjectProjectIdSchedulesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdSchedulesScheduleIdDelete
     *
     * Deletes schedule.
     *
     */
    public function testProjectProjectIdSchedulesScheduleIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdSchedulesScheduleIdGet
     *
     * Get schedule.
     *
     */
    public function testProjectProjectIdSchedulesScheduleIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for projectProjectIdSchedulesScheduleIdPut
     *
     * Updates schedule.
     *
     */
    public function testProjectProjectIdSchedulesScheduleIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
