<?php
/**
 * UserApiTest
 * PHP version 8.1
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Semaphore API
 *
 * Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models.
 *
 * The version of the OpenAPI document: 2.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientAPI\Semaphore\Test\Api;

use ClientAPI\Semaphore\Configuration;
use ClientAPI\Semaphore\ApiException;
use ClientAPI\Semaphore\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for userGet
     *
     * Fetch logged in user.
     *
     */
    public function testUserGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userTokensApiTokenIdDelete
     *
     * Expires API token.
     *
     */
    public function testUserTokensApiTokenIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userTokensGet
     *
     * Fetch API tokens for user.
     *
     */
    public function testUserTokensGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userTokensPost
     *
     * Create an API token.
     *
     */
    public function testUserTokensPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersGet
     *
     * Fetches all users.
     *
     */
    public function testUsersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersPost
     *
     * Creates a user.
     *
     */
    public function testUsersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserIdDelete
     *
     * Deletes user.
     *
     */
    public function testUsersUserIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserIdGet
     *
     * Fetches a user profile.
     *
     */
    public function testUsersUserIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserIdPasswordPost
     *
     * Updates user password.
     *
     */
    public function testUsersUserIdPasswordPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserIdPut
     *
     * Updates user details.
     *
     */
    public function testUsersUserIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
