<?php
/**
 * ScheduleApi
 * PHP version 8.1
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Semaphore API
 *
 * Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models.
 *
 * The version of the OpenAPI document: 2.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientAPI\Semaphore\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use ClientAPI\Semaphore\ApiException;
use ClientAPI\Semaphore\Configuration;
use ClientAPI\Semaphore\HeaderSelector;
use ClientAPI\Semaphore\ObjectSerializer;

/**
 * ScheduleApi Class Doc Comment
 *
 * @package  ClientAPI\Semaphore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScheduleApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'projectProjectIdSchedulesPost' => [
            'application/json',
        ],
        'projectProjectIdSchedulesScheduleIdDelete' => [
            'application/json',
        ],
        'projectProjectIdSchedulesScheduleIdGet' => [
            'application/json',
        ],
        'projectProjectIdSchedulesScheduleIdPut' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation projectProjectIdSchedulesPost
     *
     * create schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \ClientAPI\Semaphore\Model\Schedule
     */
    public function projectProjectIdSchedulesPost(
        int $projectId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesPost'][0]
    ): \ClientAPI\Semaphore\Model\Schedule
    {
        list($response) = $this->projectProjectIdSchedulesPostWithHttpInfo($projectId, $schedule, $contentType);
        return $response;
    }

    /**
     * Operation projectProjectIdSchedulesPostWithHttpInfo
     *
     * create schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \ClientAPI\Semaphore\Model\Schedule, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectProjectIdSchedulesPostWithHttpInfo(
        int $projectId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesPost'][0]
    ): array
    {
        $request = $this->projectProjectIdSchedulesPostRequest($projectId, $schedule, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\ClientAPI\Semaphore\Model\Schedule', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ClientAPI\Semaphore\Model\Schedule' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ClientAPI\Semaphore\Model\Schedule', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\ClientAPI\Semaphore\Model\Schedule';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientAPI\Semaphore\Model\Schedule',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectProjectIdSchedulesPostAsync
     *
     * create schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesPostAsync(
        int $projectId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesPost'][0]
    ): PromiseInterface
    {
        return $this->projectProjectIdSchedulesPostAsyncWithHttpInfo($projectId, $schedule, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectProjectIdSchedulesPostAsyncWithHttpInfo
     *
     * create schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesPostAsyncWithHttpInfo(
        int $projectId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesPost'][0]
    ): PromiseInterface
    {
        $returnType = '\ClientAPI\Semaphore\Model\Schedule';
        $request = $this->projectProjectIdSchedulesPostRequest($projectId, $schedule, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectProjectIdSchedulesPost'
     *
     * @param  int $projectId Project ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectProjectIdSchedulesPostRequest(
        int $projectId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesPost'][0]
    ): Request
    {

        // verify the required parameter 'projectId' is set
        if ($projectId === null || (is_array($projectId) && count($projectId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $projectId when calling projectProjectIdSchedulesPost'
            );
        }

        // verify the required parameter 'schedule' is set
        if ($schedule === null || (is_array($schedule) && count($schedule) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $schedule when calling projectProjectIdSchedulesPost'
            );
        }


        $resourcePath = '/project/{project_id}/schedules';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/plain; charset=utf-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($schedule)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($schedule));
            } else {
                $httpBody = $schedule;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cookie');
        if ($apiKey !== null) {
            $headers['Cookie'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdDelete
     *
     * Deletes schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function projectProjectIdSchedulesScheduleIdDelete(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'][0]
    ): void
    {
        $this->projectProjectIdSchedulesScheduleIdDeleteWithHttpInfo($projectId, $scheduleId, $contentType);
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdDeleteWithHttpInfo
     *
     * Deletes schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectProjectIdSchedulesScheduleIdDeleteWithHttpInfo(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'][0]
    ): array
    {
        $request = $this->projectProjectIdSchedulesScheduleIdDeleteRequest($projectId, $scheduleId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdDeleteAsync
     *
     * Deletes schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesScheduleIdDeleteAsync(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'][0]
    ): PromiseInterface
    {
        return $this->projectProjectIdSchedulesScheduleIdDeleteAsyncWithHttpInfo($projectId, $scheduleId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdDeleteAsyncWithHttpInfo
     *
     * Deletes schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesScheduleIdDeleteAsyncWithHttpInfo(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->projectProjectIdSchedulesScheduleIdDeleteRequest($projectId, $scheduleId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectProjectIdSchedulesScheduleIdDelete'
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectProjectIdSchedulesScheduleIdDeleteRequest(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdDelete'][0]
    ): Request
    {

        // verify the required parameter 'projectId' is set
        if ($projectId === null || (is_array($projectId) && count($projectId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $projectId when calling projectProjectIdSchedulesScheduleIdDelete'
            );
        }

        // verify the required parameter 'scheduleId' is set
        if ($scheduleId === null || (is_array($scheduleId) && count($scheduleId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $scheduleId when calling projectProjectIdSchedulesScheduleIdDelete'
            );
        }


        $resourcePath = '/project/{project_id}/schedules/{schedule_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($scheduleId !== null) {
            $resourcePath = str_replace(
                '{' . 'schedule_id' . '}',
                ObjectSerializer::toPathValue($scheduleId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cookie');
        if ($apiKey !== null) {
            $headers['Cookie'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdGet
     *
     * Get schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \ClientAPI\Semaphore\Model\Schedule
     */
    public function projectProjectIdSchedulesScheduleIdGet(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdGet'][0]
    ): \ClientAPI\Semaphore\Model\Schedule
    {
        list($response) = $this->projectProjectIdSchedulesScheduleIdGetWithHttpInfo($projectId, $scheduleId, $contentType);
        return $response;
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdGetWithHttpInfo
     *
     * Get schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \ClientAPI\Semaphore\Model\Schedule, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectProjectIdSchedulesScheduleIdGetWithHttpInfo(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdGet'][0]
    ): array
    {
        $request = $this->projectProjectIdSchedulesScheduleIdGetRequest($projectId, $scheduleId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\ClientAPI\Semaphore\Model\Schedule', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ClientAPI\Semaphore\Model\Schedule' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ClientAPI\Semaphore\Model\Schedule', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\ClientAPI\Semaphore\Model\Schedule';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientAPI\Semaphore\Model\Schedule',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdGetAsync
     *
     * Get schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesScheduleIdGetAsync(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdGet'][0]
    ): PromiseInterface
    {
        return $this->projectProjectIdSchedulesScheduleIdGetAsyncWithHttpInfo($projectId, $scheduleId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdGetAsyncWithHttpInfo
     *
     * Get schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesScheduleIdGetAsyncWithHttpInfo(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdGet'][0]
    ): PromiseInterface
    {
        $returnType = '\ClientAPI\Semaphore\Model\Schedule';
        $request = $this->projectProjectIdSchedulesScheduleIdGetRequest($projectId, $scheduleId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectProjectIdSchedulesScheduleIdGet'
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectProjectIdSchedulesScheduleIdGetRequest(
        int $projectId,
        int $scheduleId,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdGet'][0]
    ): Request
    {

        // verify the required parameter 'projectId' is set
        if ($projectId === null || (is_array($projectId) && count($projectId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $projectId when calling projectProjectIdSchedulesScheduleIdGet'
            );
        }

        // verify the required parameter 'scheduleId' is set
        if ($scheduleId === null || (is_array($scheduleId) && count($scheduleId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $scheduleId when calling projectProjectIdSchedulesScheduleIdGet'
            );
        }


        $resourcePath = '/project/{project_id}/schedules/{schedule_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($scheduleId !== null) {
            $resourcePath = str_replace(
                '{' . 'schedule_id' . '}',
                ObjectSerializer::toPathValue($scheduleId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/plain; charset=utf-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cookie');
        if ($apiKey !== null) {
            $headers['Cookie'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdPut
     *
     * Updates schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdPut'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function projectProjectIdSchedulesScheduleIdPut(
        int $projectId,
        int $scheduleId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdPut'][0]
    ): void
    {
        $this->projectProjectIdSchedulesScheduleIdPutWithHttpInfo($projectId, $scheduleId, $schedule, $contentType);
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdPutWithHttpInfo
     *
     * Updates schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdPut'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectProjectIdSchedulesScheduleIdPutWithHttpInfo(
        int $projectId,
        int $scheduleId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdPut'][0]
    ): array
    {
        $request = $this->projectProjectIdSchedulesScheduleIdPutRequest($projectId, $scheduleId, $schedule, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdPutAsync
     *
     * Updates schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdPut'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesScheduleIdPutAsync(
        int $projectId,
        int $scheduleId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdPut'][0]
    ): PromiseInterface
    {
        return $this->projectProjectIdSchedulesScheduleIdPutAsyncWithHttpInfo($projectId, $scheduleId, $schedule, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectProjectIdSchedulesScheduleIdPutAsyncWithHttpInfo
     *
     * Updates schedule
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdPut'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function projectProjectIdSchedulesScheduleIdPutAsyncWithHttpInfo(
        int $projectId,
        int $scheduleId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdPut'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->projectProjectIdSchedulesScheduleIdPutRequest($projectId, $scheduleId, $schedule, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectProjectIdSchedulesScheduleIdPut'
     *
     * @param  int $projectId Project ID (required)
     * @param  int $scheduleId schedule ID (required)
     * @param  \ClientAPI\Semaphore\Model\ScheduleRequest $schedule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectProjectIdSchedulesScheduleIdPut'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectProjectIdSchedulesScheduleIdPutRequest(
        int $projectId,
        int $scheduleId,
        \ClientAPI\Semaphore\Model\ScheduleRequest $schedule,
        string $contentType = self::contentTypes['projectProjectIdSchedulesScheduleIdPut'][0]
    ): Request
    {

        // verify the required parameter 'projectId' is set
        if ($projectId === null || (is_array($projectId) && count($projectId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $projectId when calling projectProjectIdSchedulesScheduleIdPut'
            );
        }

        // verify the required parameter 'scheduleId' is set
        if ($scheduleId === null || (is_array($scheduleId) && count($scheduleId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $scheduleId when calling projectProjectIdSchedulesScheduleIdPut'
            );
        }

        // verify the required parameter 'schedule' is set
        if ($schedule === null || (is_array($schedule) && count($schedule) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $schedule when calling projectProjectIdSchedulesScheduleIdPut'
            );
        }


        $resourcePath = '/project/{project_id}/schedules/{schedule_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($scheduleId !== null) {
            $resourcePath = str_replace(
                '{' . 'schedule_id' . '}',
                ObjectSerializer::toPathValue($scheduleId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($schedule)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($schedule));
            } else {
                $httpBody = $schedule;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Cookie');
        if ($apiKey !== null) {
            $headers['Cookie'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
